USE [master]
GO
/****** Object:  Database [Nxt Employee]    Script Date: 9/26/2026 11:59:20 AM ******/
CREATE DATABASE [Nxt Employee]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Nxt Employee', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Nxt Employee.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Nxt Employee_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Nxt Employee_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Nxt Employee] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Nxt Employee].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Nxt Employee] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Nxt Employee] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Nxt Employee] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Nxt Employee] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Nxt Employee] SET ARITHABORT OFF 
GO
ALTER DATABASE [Nxt Employee] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Nxt Employee] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Nxt Employee] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Nxt Employee] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Nxt Employee] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Nxt Employee] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Nxt Employee] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Nxt Employee] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Nxt Employee] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Nxt Employee] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Nxt Employee] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Nxt Employee] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Nxt Employee] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Nxt Employee] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Nxt Employee] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Nxt Employee] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Nxt Employee] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Nxt Employee] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Nxt Employee] SET  MULTI_USER 
GO
ALTER DATABASE [Nxt Employee] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Nxt Employee] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Nxt Employee] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Nxt Employee] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Nxt Employee] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Nxt Employee] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Nxt Employee] SET QUERY_STORE = ON
GO
ALTER DATABASE [Nxt Employee] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Nxt Employee]
GO
/****** Object:  Table [dbo].[NxtEmployee]    Script Date: 9/26/2026 11:59:21 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NxtEmployee](
	[Id] [bigint] NOT NULL,
	[NxtName] [varchar](20) NULL,
	[NxtGender] [bit] NULL,
	[NxtBirthday] [date] NULL,
	[NxtEmail] [varchar](50) NULL,
	[NxtPhone] [char](12) NULL,
	[NxtActive] [bit] NULL,
 CONSTRAINT [PK_NxtEmployee] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Nxt Employee] SET  READ_WRITE 
GO
